// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.noncas.domain;

import com.springsource.roo.noncas.domain.ParameterDetailIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParameterDetailIntegrationTest_Roo_Configurable {
    
    declare @type: ParameterDetailIntegrationTest: @Configurable;
    
}
