// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.noncas.domain;

import com.springsource.roo.noncas.domain.ParameterLang;
import com.springsource.roo.noncas.domain.ParameterLangDataOnDemand;
import com.springsource.roo.noncas.domain.ParameterLangIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParameterLangIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParameterLangIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParameterLangIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParameterLangIntegrationTest: @Transactional;
    
    @Autowired
    ParameterLangDataOnDemand ParameterLangIntegrationTest.dod;
    
    @Test
    public void ParameterLangIntegrationTest.testCountParameterLangs() {
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", dod.getRandomParameterLang());
        long count = ParameterLang.countParameterLangs();
        Assert.assertTrue("Counter for 'ParameterLang' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParameterLangIntegrationTest.testFindParameterLang() {
        ParameterLang obj = dod.getRandomParameterLang();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to provide an identifier", id);
        obj = ParameterLang.findParameterLang(id);
        Assert.assertNotNull("Find method for 'ParameterLang' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ParameterLang' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParameterLangIntegrationTest.testFindAllParameterLangs() {
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", dod.getRandomParameterLang());
        long count = ParameterLang.countParameterLangs();
        Assert.assertTrue("Too expensive to perform a find all test for 'ParameterLang', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ParameterLang> result = ParameterLang.findAllParameterLangs();
        Assert.assertNotNull("Find all method for 'ParameterLang' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ParameterLang' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParameterLangIntegrationTest.testFindParameterLangEntries() {
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", dod.getRandomParameterLang());
        long count = ParameterLang.countParameterLangs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ParameterLang> result = ParameterLang.findParameterLangEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ParameterLang' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ParameterLang' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParameterLangIntegrationTest.testFlush() {
        ParameterLang obj = dod.getRandomParameterLang();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to provide an identifier", id);
        obj = ParameterLang.findParameterLang(id);
        Assert.assertNotNull("Find method for 'ParameterLang' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParameterLang(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ParameterLang' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParameterLangIntegrationTest.testMergeUpdate() {
        ParameterLang obj = dod.getRandomParameterLang();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to provide an identifier", id);
        obj = ParameterLang.findParameterLang(id);
        boolean modified =  dod.modifyParameterLang(obj);
        Integer currentVersion = obj.getVersion();
        ParameterLang merged = (ParameterLang)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ParameterLang' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParameterLangIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", dod.getRandomParameterLang());
        ParameterLang obj = dod.getNewTransientParameterLang(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ParameterLang' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ParameterLang' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParameterLangIntegrationTest.testRemove() {
        ParameterLang obj = dod.getRandomParameterLang();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParameterLang' failed to provide an identifier", id);
        obj = ParameterLang.findParameterLang(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ParameterLang' with identifier '" + id + "'", ParameterLang.findParameterLang(id));
    }
    
}
